package lando.systems.ld40.gameobjects;

public enum TileType {
    COMMERCIAL_LOW_DENSITY,
    COMMERCIAL_MEDIUM_DENSITY,
    COMMERCIAL_HIGH_DENSITY,
    INDUSTRIAL_LOW_DENSITY,
    INDUSTRIAL_MEDIUM_DENSITY,
    INDUSTRIAL_HIGH_DENSITY,
    RECYCLING_CENTER,
    RESIDENTIAL_LOW_DENSITY,
    RESIDENTIAL_MEDIUM_DENSITY,
    RESIDENTIAL_HIGH_DENSITY,
}
