package lando.systems.ld40.gameobjects;

import com.badlogic.gdx.graphics.g2d.TextureRegion;
import lando.systems.ld40.utils.Assets;

public enum UpgradeType {

    DEMOLITION(Assets.testTexture, "Demolish a building"),                                             // TODO: make a texture for this
    COMPACTOR(Assets.compactorTexture, "Reduce amount of trash delivered by trucks"),
    DUMPSTER(Assets.dumpsterTexture, "Increase trash capacity of building"),
    GREEN_TOKEN(Assets.leafTexture, "Reduce amount of trash generated by building"),
    INCINERATOR(Assets.incineratorTexture, "Burn trash in a landfill over time"),
    RECLAMATION(Assets.recycleTexture, "Recycles trash in a landfill over time"),
    TIER_UPGRADE(Assets.testTexture, "Improves a building, multiplying its resource to trash ratio"),  // TODO: make a texture for this
    TRUCK(Assets.testTexture, "Add a new garbage truck");                                              // TODO: make a texture for this

    public TextureRegion texture;
    public String description;

    UpgradeType(TextureRegion texture, String description) {
        this.texture = texture;
        this.description = description;
    }

}
